import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
  >
    {/* fixed on mobile, relative on desktop */}
    <Header />

    {/* leave 64 px space under the header only on mobile */}
    <main className="flex-grow pt-16">
      {children}
    </main>

    <Footer />
  </body>
</html>

  );
}

